CREATE SCHEMA mini_asaas;
USE mini_asaas;

CREATE TABLE `devedor` (
  `ID` INT AUTO_INCREMENT PRIMARY KEY,
  `CPF_CNPJ` VARCHAR(14) NOT NULL,
  `NOME` VARCHAR(255) NOT NULL,
  `EMAIL_CONTATO` VARCHAR(254) UNIQUE NOT NULL,
  `TELEFONE_CONTATO` VARCHAR(30) UNIQUE NOT NULL,
  `ESTADO` CHAR(2) NOT NULL,
  `CIDADE` VARCHAR(255) NOT NULL,
  `ENDERECO` VARCHAR(255) NOT NULL,
  `CEP` VARCHAR(10) NOT NULL,
  `TIPO_PESSOA` VARCHAR(255) NOT NULL
);

CREATE TABLE `credor` (
  `ID` INT AUTO_INCREMENT PRIMARY KEY,
  `CPF_CNPJ` VARCHAR(14) NOT NULL,
  `NOME` VARCHAR(255) NOT NULL,
  `EMAIL_CONTATO` VARCHAR(254) UNIQUE NOT NULL,
  `TELEFONE_CONTATO` VARCHAR(30) UNIQUE NOT NULL,
  `ESTADO` CHAR(2) NOT NULL,
  `CIDADE` VARCHAR(255) NOT NULL,
  `ENDERECO` VARCHAR(255) NOT NULL,
  `CEP` VARCHAR(10) NOT NULL,
  `TIPO_PESSOA` VARCHAR(255) NOT NULL
);

CREATE TABLE `cobranca` (
  `ID` INT AUTO_INCREMENT PRIMARY KEY,
  `VALOR` DECIMAL(10,2) NOT NULL,
  `DESCRICAO` TEXT,
  `DATA_VENCIMENTO` DATE NOT NULL,
  `ID_CREDOR` INT NOT NULL,
  `ID_DEVEDOR` INT NOT NULL,
  `COBRANCA_STATUS` VARCHAR(255) NOT NULL DEFAULT 'PENDENTE',
  FOREIGN KEY (`ID_DEVEDOR`) REFERENCES `devedor`(`ID`),
  FOREIGN KEY (`ID_CREDOR`) REFERENCES `credor`(`ID`)
);