CREATE SCHEMA mini_asaas;
USE mini_asaas;

CREATE TABLE `cliente` (
  `ID` CHAR(36) PRIMARY KEY DEFAULT (UUID()),
  `CPF` CHAR(11) UNIQUE NOT NULL,
  `NOME` VARCHAR(255) NOT NULL,
  `EMAIL_CONTATO` VARCHAR(254) UNIQUE NOT NULL,
  `TELEFONE_CONTATO` VARCHAR(30) UNIQUE NOT NULL,
  `ESTADO` CHAR(2) NOT NULL,
  `CIDADE` VARCHAR(255) NOT NULL,
  `BAIRRO` VARCHAR(255) NOT NULL,
  `CEP` CHAR(8) NOT NULL
);

CREATE TABLE `empresa` (
  `ID` CHAR(36) PRIMARY KEY DEFAULT (UUID()),
  `RAZAO_SOCIAL` VARCHAR(255) UNIQUE NOT NULL,
  `CNPJ` CHAR(14) UNIQUE NOT NULL,
  `NOME_FANTASIA` VARCHAR(255) NOT NULL,
  `RESPONSAVEL` VARCHAR(255) NOT NULL,
  `ESTADO` CHAR(2) NOT NULL,
  `CIDADE` VARCHAR(255) NOT NULL,
  `BAIRRO` VARCHAR(255) NOT NULL,
  `CEP` CHAR(8) NOT NULL,
  `EMAIL_CONTATO` VARCHAR(254) UNIQUE NOT NULL,
  `TELEFONE_CONTATO` VARCHAR(30) UNIQUE NOT NULL
);

CREATE TABLE `cobranca` (
  `ID` CHAR(36) PRIMARY KEY DEFAULT (UUID()),
  `VALOR` DECIMAL(10,2) NOT NULL,
  `DESCRICAO` TEXT,
  `DATA_VENCIMENTO` DATE NOT NULL,
  `ID_CLIENTE` CHAR(36) NOT NULL,
  `ID_EMPRESA` CHAR(36) NOT NULL,
  `STATUS` VARCHAR(255) NOT NULL DEFAULT 'PENDENTE',
  FOREIGN KEY (`ID_CLIENTE`) REFERENCES `cliente`(`ID`),
  FOREIGN KEY (`ID_EMPRESA`) REFERENCES `empresa`(`ID`),
  CHECK (`STATUS` IN (`PENDENTE`,`VENCIDA`,`PAGA`))
);