CREATE SCHEMA mini_asaas;
USE mini_asaas;

CREATE TABLE `devedor` (
  `ID` CHAR(36) PRIMARY KEY DEFAULT (UUID()),
  `CPF_CNPJ` VARCHAR(14) NOT NULL,
  `NOME` VARCHAR(255) NOT NULL,
  `EMAIL_CONTATO` VARCHAR(254) UNIQUE NOT NULL,
  `TELEFONE_CONTATO` VARCHAR(30) UNIQUE NOT NULL,
  `ESTADO` CHAR(2) NOT NULL,
  `CIDADE` VARCHAR(255) NOT NULL,
  `ENDERECO` VARCHAR(255) NOT NULL,
  `CEP` CHAR(8) NOT NULL,
  `PERSON_TYPE` CHAR(2) NOT NULL,
  CHECK (`PERSON_TYPE` IN ('PF', 'PJ')),
  CHECK (
    (`PERSON_TYPE` = 'PF' AND LENGTH(`CPF_CNPJ`) = 11) OR
    (`PERSON_TYPE` = 'PJ' AND LENGTH(`CPF_CNPJ`) = 14)
  )
);

CREATE TABLE `credor` (
  `ID` CHAR(36) PRIMARY KEY DEFAULT (UUID()),
  `CPF_CNPJ` VARCHAR(14) NOT NULL,
  `NOME` VARCHAR(255) NOT NULL,
  `EMAIL_CONTATO` VARCHAR(254) UNIQUE NOT NULL,
  `TELEFONE_CONTATO` VARCHAR(30) UNIQUE NOT NULL,
  `ESTADO` CHAR(2) NOT NULL,
  `CIDADE` VARCHAR(255) NOT NULL,
  `ENDERECO` VARCHAR(255) NOT NULL,
  `CEP` CHAR(8) NOT NULL,
  `PERSON_TYPE` CHAR(2) NOT NULL,
  CHECK (`PERSON_TYPE` IN ('PF', 'PJ')),
  CHECK (
    (`PERSON_TYPE` = 'PF' AND LENGTH(`CPF_CNPJ`) = 11) OR
    (`PERSON_TYPE` = 'PJ' AND LENGTH(`CPF_CNPJ`) = 14)
  )
);

CREATE TABLE `cobranca` (
  `ID` CHAR(36) PRIMARY KEY DEFAULT (UUID()),
  `VALOR` DECIMAL(10,2) NOT NULL,
  `DESCRICAO` TEXT,
  `DATA_VENCIMENTO` DATE NOT NULL,
  `ID_CREDOR` CHAR(36) NOT NULL,
  `ID_DEVEDOR` CHAR(36) NOT NULL,
  `COBRANCA_STATUS` VARCHAR(255) NOT NULL DEFAULT 'PENDENTE',
  FOREIGN KEY (`ID_DEVEDOR`) REFERENCES `devedor`(`ID`),
  FOREIGN KEY (`ID_CREDOR`) REFERENCES `credor`(`ID`),
  CHECK (`COBRANCA_STATUS` IN ('PENDENTE','VENCIDA','PAGA'))
);